<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_about',
		'title' => 'About',
		'fields' => array (
			array (
				'key' => 'field_55a1c51037c2b',
				'label' => 'Content',
				'name' => 'arfi_about_content',
				'type' => 'flexible_content',
				'instructions' => 'Add different content in your about page.',
				'layouts' => array (
					array (
						'label' => 'Skills',
						'name' => 'arfi_about_content_skills',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_55a1c5561b3a9',
								'label' => 'Skill',
								'name' => 'arfi_about_content_skills_loop',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55a1c57b1b3aa',
										'label' => 'Name',
										'name' => 'arfi_about_content_skills_loop_name',
										'type' => 'text',
										'instructions' => 'Name of skill.',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_55a1c5891b3ab',
										'label' => 'Percentage',
										'name' => 'arfi_about_content_skills_loop_percentage',
										'type' => 'number',
										'instructions' => 'Percentage of Skill from 1 to 100.',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'min' => 1,
										'max' => 100,
										'step' => 1,
									),
								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add a skill',
							),
						),
					),
					array (
						'label' => 'Social icons',
						'name' => 'arfi_about_content_socials',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_55a1c6371b3b0',
								'label' => 'Icon',
								'name' => 'arfi_about_content_socials_loop',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55a1c6521b3b1',
										'label' => 'Icon',
										'name' => 'arfi_about_content_socials_loop_icon',
										'type' => 'font-awesome',
										'column_width' => '',
										'default_value' => 'null',
										'save_format' => 'class',
										'allow_null' => 0,
										'enqueue_fa' => 0,
										'choices' => array (
											'fa-adjust' => '',
											'fa-adn' => '',
											'fa-align-center' => '',
											'fa-align-justify' => '',
											'fa-align-left' => '',
											'fa-align-right' => '',
											'fa-ambulance' => '',
											'fa-anchor' => '',
											'fa-android' => '',
											'fa-angle-double-down' => '',
											'fa-angle-double-left' => '',
											'fa-angle-double-right' => '',
											'fa-angle-double-up' => '',
											'fa-angle-down' => '',
											'fa-angle-left' => '',
											'fa-angle-right' => '',
											'fa-angle-up' => '',
											'fa-apple' => '',
											'fa-archive' => '',
											'fa-arrow-circle-down' => '',
											'fa-arrow-circle-left' => '',
											'fa-arrow-circle-o-down' => '',
											'fa-arrow-circle-o-left' => '',
											'fa-arrow-circle-o-right' => '',
											'fa-arrow-circle-o-up' => '',
											'fa-arrow-circle-right' => '',
											'fa-arrow-circle-up' => '',
											'fa-arrow-down' => '',
											'fa-arrow-left' => '',
											'fa-arrow-right' => '',
											'fa-arrow-up' => '',
											'fa-arrows' => '',
											'fa-arrows-alt' => '',
											'fa-arrows-h' => '',
											'fa-arrows-v' => '',
											'fa-asterisk' => '',
											'fa-automobile' => '',
											'fa-backward' => '',
											'fa-ban' => '',
											'fa-bank' => '',
											'fa-bar-chart-o' => '',
											'fa-barcode' => '',
											'fa-bars' => '',
											'fa-beer' => '',
											'fa-behance' => '',
											'fa-behance-square' => '',
											'fa-bell' => '',
											'fa-bell-o' => '',
											'fa-bitbucket' => '',
											'fa-bitbucket-square' => '',
											'fa-bitcoin' => '',
											'fa-bold' => '',
											'fa-bolt' => '',
											'fa-bomb' => '',
											'fa-book' => '',
											'fa-bookmark' => '',
											'fa-bookmark-o' => '',
											'fa-briefcase' => '',
											'fa-btc' => '',
											'fa-bug' => '',
											'fa-building' => '',
											'fa-building-o' => '',
											'fa-bullhorn' => '',
											'fa-bullseye' => '',
											'fa-cab' => '',
											'fa-calendar' => '',
											'fa-calendar-o' => '',
											'fa-camera' => '',
											'fa-camera-retro' => '',
											'fa-car' => '',
											'fa-caret-down' => '',
											'fa-caret-left' => '',
											'fa-caret-right' => '',
											'fa-caret-square-o-down' => '',
											'fa-caret-square-o-left' => '',
											'fa-caret-square-o-right' => '',
											'fa-caret-square-o-up' => '',
											'fa-caret-up' => '',
											'fa-certificate' => '',
											'fa-chain' => '',
											'fa-chain-broken' => '',
											'fa-check' => '',
											'fa-check-circle' => '',
											'fa-check-circle-o' => '',
											'fa-check-square' => '',
											'fa-check-square-o' => '',
											'fa-chevron-circle-down' => '',
											'fa-chevron-circle-left' => '',
											'fa-chevron-circle-right' => '',
											'fa-chevron-circle-up' => '',
											'fa-chevron-down' => '',
											'fa-chevron-left' => '',
											'fa-chevron-right' => '',
											'fa-chevron-up' => '',
											'fa-child' => '',
											'fa-circle' => '',
											'fa-circle-o' => '',
											'fa-circle-o-notch' => '',
											'fa-circle-thin' => '',
											'fa-clipboard' => '',
											'fa-clock-o' => '',
											'fa-cloud' => '',
											'fa-cloud-download' => '',
											'fa-cloud-upload' => '',
											'fa-cny' => '',
											'fa-code' => '',
											'fa-code-fork' => '',
											'fa-codepen' => '',
											'fa-coffee' => '',
											'fa-cog' => '',
											'fa-cogs' => '',
											'fa-columns' => '',
											'fa-comment' => '',
											'fa-comment-o' => '',
											'fa-comments' => '',
											'fa-comments-o' => '',
											'fa-compass' => '',
											'fa-compress' => '',
											'fa-copy' => '',
											'fa-credit-card' => '',
											'fa-crop' => '',
											'fa-crosshairs' => '',
											'fa-css3' => '',
											'fa-cube' => '',
											'fa-cubes' => '',
											'fa-cut' => '',
											'fa-cutlery' => '',
											'fa-dashboard' => '',
											'fa-database' => '',
											'fa-dedent' => '',
											'fa-delicious' => '',
											'fa-desktop' => '',
											'fa-deviantart' => '',
											'fa-digg' => '',
											'fa-dollar' => '',
											'fa-dot-circle-o' => '',
											'fa-download' => '',
											'fa-dribbble' => '',
											'fa-dropbox' => '',
											'fa-drupal' => '',
											'fa-edit' => '',
											'fa-eject' => '',
											'fa-ellipsis-h' => '',
											'fa-ellipsis-v' => '',
											'fa-empire' => '',
											'fa-envelope' => '',
											'fa-envelope-o' => '',
											'fa-envelope-square' => '',
											'fa-eraser' => '',
											'fa-eur' => '',
											'fa-euro' => '',
											'fa-exchange' => '',
											'fa-exclamation' => '',
											'fa-exclamation-circle' => '',
											'fa-exclamation-triangle' => '',
											'fa-expand' => '',
											'fa-external-link' => '',
											'fa-external-link-square' => '',
											'fa-eye' => '',
											'fa-eye-slash' => '',
											'fa-facebook' => '',
											'fa-facebook-square' => '',
											'fa-fast-backward' => '',
											'fa-fast-forward' => '',
											'fa-fax' => '',
											'fa-female' => '',
											'fa-fighter-jet' => '',
											'fa-file' => '',
											'fa-file-archive-o' => '',
											'fa-file-audio-o' => '',
											'fa-file-code-o' => '',
											'fa-file-excel-o' => '',
											'fa-file-image-o' => '',
											'fa-file-movie-o' => '',
											'fa-file-o' => '',
											'fa-file-pdf-o' => '',
											'fa-file-photo-o' => '',
											'fa-file-picture-o' => '',
											'fa-file-powerpoint-o' => '',
											'fa-file-sound-o' => '',
											'fa-file-text' => '',
											'fa-file-text-o' => '',
											'fa-file-video-o' => '',
											'fa-file-word-o' => '',
											'fa-file-zip-o' => '',
											'fa-files-o' => '',
											'fa-film' => '',
											'fa-filter' => '',
											'fa-fire' => '',
											'fa-fire-extinguisher' => '',
											'fa-flag' => '',
											'fa-flag-checkered' => '',
											'fa-flag-o' => '',
											'fa-flash' => '',
											'fa-flask' => '',
											'fa-flickr' => '',
											'fa-floppy-o' => '',
											'fa-folder' => '',
											'fa-folder-o' => '',
											'fa-folder-open' => '',
											'fa-folder-open-o' => '',
											'fa-font' => '',
											'fa-forward' => '',
											'fa-foursquare' => '',
											'fa-frown-o' => '',
											'fa-gamepad' => '',
											'fa-gavel' => '',
											'fa-gbp' => '',
											'fa-ge' => '',
											'fa-gear' => '',
											'fa-gears' => '',
											'fa-gift' => '',
											'fa-git' => '',
											'fa-git-square' => '',
											'fa-github' => '',
											'fa-github-alt' => '',
											'fa-github-square' => '',
											'fa-gittip' => '',
											'fa-glass' => '',
											'fa-globe' => '',
											'fa-google' => '',
											'fa-google-plus' => '',
											'fa-google-plus-square' => '',
											'fa-graduation-cap' => '',
											'fa-group' => '',
											'fa-h-square' => '',
											'fa-hacker-news' => '',
											'fa-hand-o-down' => '',
											'fa-hand-o-left' => '',
											'fa-hand-o-right' => '',
											'fa-hand-o-up' => '',
											'fa-hdd-o' => '',
											'fa-header' => '',
											'fa-headphones' => '',
											'fa-heart' => '',
											'fa-heart-o' => '',
											'fa-history' => '',
											'fa-home' => '',
											'fa-hospital-o' => '',
											'fa-html5' => '',
											'fa-image' => '',
											'fa-inbox' => '',
											'fa-indent' => '',
											'fa-info' => '',
											'fa-info-circle' => '',
											'fa-inr' => '',
											'fa-instagram' => '',
											'fa-institution' => '',
											'fa-italic' => '',
											'fa-joomla' => '',
											'fa-jpy' => '',
											'fa-jsfiddle' => '',
											'fa-key' => '',
											'fa-keyboard-o' => '',
											'fa-krw' => '',
											'fa-language' => '',
											'fa-laptop' => '',
											'fa-leaf' => '',
											'fa-legal' => '',
											'fa-lemon-o' => '',
											'fa-level-down' => '',
											'fa-level-up' => '',
											'fa-life-bouy' => '',
											'fa-life-ring' => '',
											'fa-life-saver' => '',
											'fa-lightbulb-o' => '',
											'fa-link' => '',
											'fa-linkedin' => '',
											'fa-linkedin-square' => '',
											'fa-linux' => '',
											'fa-list' => '',
											'fa-list-alt' => '',
											'fa-list-ol' => '',
											'fa-list-ul' => '',
											'fa-location-arrow' => '',
											'fa-lock' => '',
											'fa-long-arrow-down' => '',
											'fa-long-arrow-left' => '',
											'fa-long-arrow-right' => '',
											'fa-long-arrow-up' => '',
											'fa-magic' => '',
											'fa-magnet' => '',
											'fa-mail-forward' => '',
											'fa-mail-reply' => '',
											'fa-mail-reply-all' => '',
											'fa-male' => '',
											'fa-map-marker' => '',
											'fa-maxcdn' => '',
											'fa-medkit' => '',
											'fa-meh-o' => '',
											'fa-microphone' => '',
											'fa-microphone-slash' => '',
											'fa-minus' => '',
											'fa-minus-circle' => '',
											'fa-minus-square' => '',
											'fa-minus-square-o' => '',
											'fa-mobile' => '',
											'fa-mobile-phone' => '',
											'fa-money' => '',
											'fa-moon-o' => '',
											'fa-mortar-board' => '',
											'fa-music' => '',
											'fa-navicon' => '',
											'fa-openid' => '',
											'fa-outdent' => '',
											'fa-pagelines' => '',
											'fa-paper-plane' => '',
											'fa-paper-plane-o' => '',
											'fa-paperclip' => '',
											'fa-paragraph' => '',
											'fa-paste' => '',
											'fa-pause' => '',
											'fa-paw' => '',
											'fa-pencil' => '',
											'fa-pencil-square' => '',
											'fa-pencil-square-o' => '',
											'fa-phone' => '',
											'fa-phone-square' => '',
											'fa-photo' => '',
											'fa-picture-o' => '',
											'fa-pied-piper' => '',
											'fa-pied-piper-alt' => '',
											'fa-pied-piper-square' => '',
											'fa-pinterest' => '',
											'fa-pinterest-square' => '',
											'fa-plane' => '',
											'fa-play' => '',
											'fa-play-circle' => '',
											'fa-play-circle-o' => '',
											'fa-plus' => '',
											'fa-plus-circle' => '',
											'fa-plus-square' => '',
											'fa-plus-square-o' => '',
											'fa-power-off' => '',
											'fa-print' => '',
											'fa-puzzle-piece' => '',
											'fa-qq' => '',
											'fa-qrcode' => '',
											'fa-question' => '',
											'fa-question-circle' => '',
											'fa-quote-left' => '',
											'fa-quote-right' => '',
											'fa-ra' => '',
											'fa-random' => '',
											'fa-rebel' => '',
											'fa-recycle' => '',
											'fa-reddit' => '',
											'fa-reddit-square' => '',
											'fa-refresh' => '',
											'fa-renren' => '',
											'fa-reorder' => '',
											'fa-repeat' => '',
											'fa-reply' => '',
											'fa-reply-all' => '',
											'fa-retweet' => '',
											'fa-rmb' => '',
											'fa-road' => '',
											'fa-rocket' => '',
											'fa-rotate-left' => '',
											'fa-rotate-right' => '',
											'fa-rouble' => '',
											'fa-rss' => '',
											'fa-rss-square' => '',
											'fa-rub' => '',
											'fa-ruble' => '',
											'fa-rupee' => '',
											'fa-save' => '',
											'fa-scissors' => '',
											'fa-search' => '',
											'fa-search-minus' => '',
											'fa-search-plus' => '',
											'fa-send' => '',
											'fa-send-o' => '',
											'fa-share' => '',
											'fa-share-alt' => '',
											'fa-share-alt-square' => '',
											'fa-share-square' => '',
											'fa-share-square-o' => '',
											'fa-shield' => '',
											'fa-shopping-cart' => '',
											'fa-sign-in' => '',
											'fa-sign-out' => '',
											'fa-signal' => '',
											'fa-sitemap' => '',
											'fa-skype' => '',
											'fa-slack' => '',
											'fa-sliders' => '',
											'fa-smile-o' => '',
											'fa-sort' => '',
											'fa-sort-alpha-asc' => '',
											'fa-sort-alpha-desc' => '',
											'fa-sort-amount-asc' => '',
											'fa-sort-amount-desc' => '',
											'fa-sort-asc' => '',
											'fa-sort-desc' => '',
											'fa-sort-down' => '',
											'fa-sort-numeric-asc' => '',
											'fa-sort-numeric-desc' => '',
											'fa-sort-up' => '',
											'fa-soundcloud' => '',
											'fa-space-shuttle' => '',
											'fa-spinner' => '',
											'fa-spoon' => '',
											'fa-spotify' => '',
											'fa-square' => '',
											'fa-square-o' => '',
											'fa-stack-exchange' => '',
											'fa-stack-overflow' => '',
											'fa-star' => '',
											'fa-star-half' => '',
											'fa-star-half-empty' => '',
											'fa-star-half-full' => '',
											'fa-star-half-o' => '',
											'fa-star-o' => '',
											'fa-steam' => '',
											'fa-steam-square' => '',
											'fa-step-backward' => '',
											'fa-step-forward' => '',
											'fa-stethoscope' => '',
											'fa-stop' => '',
											'fa-strikethrough' => '',
											'fa-stumbleupon' => '',
											'fa-stumbleupon-circle' => '',
											'fa-subscript' => '',
											'fa-suitcase' => '',
											'fa-sun-o' => '',
											'fa-superscript' => '',
											'fa-support' => '',
											'fa-table' => '',
											'fa-tablet' => '',
											'fa-tachometer' => '',
											'fa-tag' => '',
											'fa-tags' => '',
											'fa-tasks' => '',
											'fa-taxi' => '',
											'fa-tencent-weibo' => '',
											'fa-terminal' => '',
											'fa-text-height' => '',
											'fa-text-width' => '',
											'fa-th' => '',
											'fa-th-large' => '',
											'fa-th-list' => '',
											'fa-thumb-tack' => '',
											'fa-thumbs-down' => '',
											'fa-thumbs-o-down' => '',
											'fa-thumbs-o-up' => '',
											'fa-thumbs-up' => '',
											'fa-ticket' => '',
											'fa-times' => '',
											'fa-times-circle' => '',
											'fa-times-circle-o' => '',
											'fa-tint' => '',
											'fa-toggle-down' => '',
											'fa-toggle-left' => '',
											'fa-toggle-right' => '',
											'fa-toggle-up' => '',
											'fa-trash-o' => '',
											'fa-tree' => '',
											'fa-trello' => '',
											'fa-trophy' => '',
											'fa-truck' => '',
											'fa-try' => '',
											'fa-tumblr' => '',
											'fa-tumblr-square' => '',
											'fa-turkish-lira' => '',
											'fa-twitter' => '',
											'fa-twitter-square' => '',
											'fa-umbrella' => '',
											'fa-underline' => '',
											'fa-undo' => '',
											'fa-university' => '',
											'fa-unlink' => '',
											'fa-unlock' => '',
											'fa-unlock-alt' => '',
											'fa-unsorted' => '',
											'fa-upload' => '',
											'fa-usd' => '',
											'fa-user' => '',
											'fa-user-md' => '',
											'fa-users' => '',
											'fa-video-camera' => '',
											'fa-vimeo-square' => '',
											'fa-vine' => '',
											'fa-vk' => '',
											'fa-volume-down' => '',
											'fa-volume-off' => '',
											'fa-volume-up' => '',
											'fa-warning' => '',
											'fa-wechat' => '',
											'fa-weibo' => '',
											'fa-weixin' => '',
											'fa-wheelchair' => '',
											'fa-windows' => '',
											'fa-won' => '',
											'fa-wordpress' => '',
											'fa-wrench' => '',
											'fa-xing' => '',
											'fa-xing-square' => '',
											'fa-yahoo' => '',
											'fa-yen' => '',
											'fa-youtube' => '',
											'fa-youtube-play' => '',
											'fa-youtube-square' => '',
										),
									),
									array (
										'key' => 'field_55a1c6761b3b2',
										'label' => 'Link',
										'name' => 'arfi_about_content_socials_loop_link',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add an icon',
							),
						),
					),
					array (
						'label' => 'Clients',
						'name' => 'arfi_about_content_clients',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_55a1c7da1b3b4',
								'label' => 'Client',
								'name' => 'arfi_about_content_clients_loop',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55a1c7e61b3b5',
										'label' => 'Image',
										'name' => 'arfi_about_content_socials_loop_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 0,
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add a client.',
							),
						),
					),
				),
				'button_label' => 'Add Different Content',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog',
		'title' => 'Blog',
		'fields' => array (
			array (
				'key' => 'field_55a1cb1860b33',
				'label' => 'Category',
				'name' => 'arfi_blog_category',
				'type' => 'taxonomy',
				'instructions' => 'Choose the category where you want to get the posts from.',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_55a1cb4a0082c',
				'label' => 'Post per page',
				'name' => 'arfi_blog_postperpage',
				'type' => 'number',
				'instructions' => 'Write how many post per page you want in blog, default is 5.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_55a1cd96f8c3d',
				'label' => 'Layout',
				'name' => 'arfi_blog_layout',
				'type' => 'radio',
				'instructions' => 'Choose your blog layout, default is classic.',
				'choices' => array (
					1 => 'Classic <br> <img style="padding-top:15px;" src="http://s23.postimg.org/pue60ktdj/blog_classic.png">',
					2 => 'Wide <br> <img style="padding-top:15px;" src="http://s23.postimg.org/p69wvdk1j/blog_wide.png">',
					3 => 'Masonry v1 <br> <img style="padding-top:15px;" src="http://s23.postimg.org/elzzcsfjr/grid_v2.png">',
					4 => 'Masonry v2 <br> <img style="padding-top:15px;" src="http://s23.postimg.org/6f7zl7ph3/grid_v1.png">',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-blog.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact',
		'title' => 'Contact',
		'fields' => array (
			array (
				'key' => 'field_55a32a155b35c',
				'label' => 'Contact Form',
				'name' => 'arfi_contact_form',
				'type' => 'acf_cf7',
				'instructions' => 'Select your contact form.',
				'allow_null' => 0,
				'multiple' => 0,
				'disable' => array (
					0 => 0,
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_help',
		'title' => 'Help!',
		'fields' => array (
			array (
				'key' => 'field_55db1b4f738f9',
				'label' => 'arfi',
				'name' => '',
				'type' => 'message',
				'message' => '<h2>Included Styling for Plugins</h2>
	<p>At current version, arfi provides 100% CSS support only for the Contact Form 7 plugin. This means that the messages and notifications from the plugin will be combined nicely with the theme style. We are working to provide support for as many plugins as possible. </p>
	<h2>How to Update</h2>
	<p>You can update your theme by downloading a fresh copy from ThemeForest, deleting the current version you have on your server and uploading the new. It\'s recommended that you use FTP, but this also can be done with the WP dashboard if you prefer.</p>
	<h2>Dummy Data</h2>
	<p>If you don\'t want to start from scratch and setup the theme by yourself, you can use the dummy data (dummy_data.xml) provided in the package you downloaded from ThemeForest. You must go to WordPress admin panel, and use Tools > Import page to import. Click WordPress, install the plugin and import the XML file. If you want attachments and images to be downloaded to your website, check the option. Otherwise, leave it unchecked. If you choose to save the images, it can take a couple minutes to be finished, so plase be patient. After you get the success message, the only thing left would be to setup the menu.</p>
	<p>							<br></p>
	<h2>Conclusion</h2>
	<p>Thanks for purchasing our theme. We hope it wil be useful in your project, and this documentation was clear enough to guide you on setting up your website with our theme. If you need support, or custom work, please contact us at <a href="#">illyrianthemes@gmail.com</a> </p>',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-help',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-title',
		'title' => 'Page Title',
		'fields' => array (
			array (
				'key' => 'field_55a1a43061020',
				'label' => 'Image',
				'name' => 'arfi_pagetitle_background_image',
				'type' => 'image',
				'instructions' => 'Upload your background image behind page title, default is pattern from the theme.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_55a1a49461021',
				'label' => 'Title',
				'name' => 'arfi_pagetitle_title',
				'type' => 'text',
				'instructions' => 'Page title of the page or post, if you don\'t write anything it will pickup the default title.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55a1a4a561022',
				'label' => 'Description',
				'name' => 'arfi_pagetitle_description',
				'type' => 'textarea',
				'instructions' => 'Write the page description.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-blog.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-contact.php',
					'order_no' => 0,
					'group_no' => 3,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-portfolio.php',
					'order_no' => 0,
					'group_no' => 4,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 5,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio',
		'title' => 'Portfolio',
		'fields' => array (
			array (
				'key' => 'field_55a3cf4670733',
				'label' => 'Category',
				'name' => 'arfi_portfolio_category',
				'type' => 'taxonomy',
				'instructions' => 'Choose the category where you want to get the posts from.',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_55a3d0fecdf6b',
				'label' => 'Layout',
				'name' => 'arfi_portfolio_layout',
				'type' => 'radio',
				'instructions' => 'Choose your portfolio layout.',
				'choices' => array (
					1 => 'Grid - 2 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/2columns.png">',
					2 => 'Grid - 3 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/3columns.png">',
					3 => 'Grid - 4 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/4columns.png">',
					4 => 'Masonry - 2 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/masonry-2col.png">',
					5 => 'Masonry - 3 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/masonry.png">',
					6 => 'Masonry - 4 Columns <br> <img style="padding-top:15px;" src="http://illyrianthemes.com/gallery/masonry-4col.png">',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55be42b57cca8',
				'label' => 'Filters',
				'name' => 'arfi_portfolio_filters',
				'type' => 'true_false',
				'instructions' => 'If checked, portfolio items will be grouped by filters (represented by tags).',
				'message' => 'Enable filters',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55be43087cca9',
				'label' => 'Filter Tags',
				'name' => 'arfi_portfolio_filter_tags',
				'type' => 'taxonomy',
				'instructions' => 'Select the tags which you want to use as filters for the portfolio items. Hold ctrl(control) keyboard key for multiple tags.',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55be42b57cca8',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'post_tag',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-portfolio.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post',
		'title' => 'Post',
		'fields' => array (
			array (
				'key' => 'field_55a1d4ac66249',
				'label' => 'Post Type',
				'name' => 'post_type',
				'type' => 'radio',
				'instructions' => 'Choose your single layout.',
				'required' => 1,
				'choices' => array (
					1 => 'Blog Single',
					2 => 'Portfolio Single',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55a70f19b8096',
				'label' => 'Layout',
				'name' => 'arfi_portfolio_single_layout',
				'type' => 'radio',
				'instructions' => 'Choose your portfolio single layout.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55a1d4ac66249',
							'operator' => '==',
							'value' => '2',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					1 => 'Single 1 <br> <img style="padding-top:15px; width:200px; height:auto;" src="http://illyrianthemes.com/gallery/single1.png">',
					2 => 'Single 2 <br> <img style="padding-top:15px; width:200px; height:auto;" src="http://illyrianthemes.com/gallery/single2.png">',
					3 => 'Single 3 <br> <img style="padding-top:15px; width:200px; height:auto;" src="http://illyrianthemes.com/gallery/single3.png">',
					4 => 'Single 4 <br> <img style="padding-top:15px; width:200px; height:auto;" src="http://illyrianthemes.com/gallery/single4.png">',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55a733abe0005',
				'label' => 'Gallery',
				'name' => 'arfi_portfolio_single_gallery',
				'type' => 'repeater',
				'instructions' => 'Upload images in your single project gallery.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55a1d4ac66249',
							'operator' => '==',
							'value' => '2',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_55a733c8e0006',
						'label' => 'Image',
						'name' => 'arfi_portfolio_single_gallery_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add an image',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_settings',
		'title' => 'Settings',
		'fields' => array (
			array (
				'key' => 'field_55a1a2c1ee88c',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55a1a62d374a9',
				'label' => 'Favicon',
				'name' => 'arfi_favicon',
				'type' => 'image',
				'instructions' => 'Upload your favicon.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55a1c996fb17f',
				'label' => 'Background pattern',
				'name' => 'arfi_background_pattern',
				'type' => 'image',
				'instructions' => 'Upload a default image for non background image pages, if you don\'t upload any there is a great pattern from the theme.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55a1ca4d1e044',
				'label' => 'Background pattern repeat',
				'name' => 'arfi_background_pattern_repeat',
				'type' => 'radio',
				'instructions' => 'Fix or change the repeat style of upper field image, default is repeat.',
				'choices' => array (
					1 => 'Repeat',
					2 => 'Repeat-X',
					3 => 'Repeat-Y',
					4 => 'No-Repeat',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55ad3641a87ef',
				'label' => 'Transition effect',
				'name' => 'arfi_transition_effect',
				'type' => 'radio',
				'instructions' => 'Enable or Disable the transition effect of elements, Default is enable.',
				'choices' => array (
					1 => 'Enable',
					2 => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 1,
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55ad36e66a48f',
				'label' => 'Transition duration',
				'name' => 'arfi_transition_duration',
				'type' => 'number',
				'instructions' => 'Change the transition effect duration. Default is 0.3 seconds.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55ad3641a87ef',
							'operator' => '!=',
							'value' => '2',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '0.1',
				'max' => '',
				'step' => '0.1',
			),
			array (
				'key' => 'field_55a1a2c7ee88d',
				'label' => 'Style',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55ae2bf327bd3',
				'label' => 'Main color',
				'name' => 'arfi_main_color',
				'type' => 'color_picker',
				'instructions' => 'Change the main color of the website, which will override all the elements main colors.',
				'default_value' => '',
			),
			array (
				'key' => 'field_55d1efb4baafd',
				'label' => 'Header of page title',
				'name' => 'arfi_page_title_header_color',
				'type' => 'color_picker',
				'instructions' => 'Change the color of page title header.',
				'default_value' => '',
			),
			array (
				'key' => 'field_55d1fbcaab8b6',
				'label' => 'Content of page title',
				'name' => 'arfi_page_title_content_color',
				'type' => 'color_picker',
				'instructions' => 'Change the color of page title content.',
				'default_value' => '',
			),
			array (
				'key' => 'field_55a1a320ee88e',
				'label' => 'Header',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55a1a5a490c39',
				'label' => 'Logo',
				'name' => 'arfi_logo',
				'type' => 'image',
				'instructions' => 'Upload your logo.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55a1a81557839',
				'label' => 'Social icons',
				'name' => 'arfi_header_icons',
				'type' => 'repeater',
				'instructions' => 'Add your social icons in Header.',
				'sub_fields' => array (
					array (
						'key' => 'field_55a1a8375783a',
						'label' => 'Icon',
						'name' => 'arfi_header_icons_icon',
						'type' => 'font-awesome',
						'column_width' => '',
						'default_value' => 'null',
						'save_format' => 'class',
						'allow_null' => 0,
						'enqueue_fa' => 0,
						'choices' => array (
							'fa-adjust' => '',
							'fa-adn' => '',
							'fa-align-center' => '',
							'fa-align-justify' => '',
							'fa-align-left' => '',
							'fa-align-right' => '',
							'fa-ambulance' => '',
							'fa-anchor' => '',
							'fa-android' => '',
							'fa-angle-double-down' => '',
							'fa-angle-double-left' => '',
							'fa-angle-double-right' => '',
							'fa-angle-double-up' => '',
							'fa-angle-down' => '',
							'fa-angle-left' => '',
							'fa-angle-right' => '',
							'fa-angle-up' => '',
							'fa-apple' => '',
							'fa-archive' => '',
							'fa-arrow-circle-down' => '',
							'fa-arrow-circle-left' => '',
							'fa-arrow-circle-o-down' => '',
							'fa-arrow-circle-o-left' => '',
							'fa-arrow-circle-o-right' => '',
							'fa-arrow-circle-o-up' => '',
							'fa-arrow-circle-right' => '',
							'fa-arrow-circle-up' => '',
							'fa-arrow-down' => '',
							'fa-arrow-left' => '',
							'fa-arrow-right' => '',
							'fa-arrow-up' => '',
							'fa-arrows' => '',
							'fa-arrows-alt' => '',
							'fa-arrows-h' => '',
							'fa-arrows-v' => '',
							'fa-asterisk' => '',
							'fa-automobile' => '',
							'fa-backward' => '',
							'fa-ban' => '',
							'fa-bank' => '',
							'fa-bar-chart-o' => '',
							'fa-barcode' => '',
							'fa-bars' => '',
							'fa-beer' => '',
							'fa-behance' => '',
							'fa-behance-square' => '',
							'fa-bell' => '',
							'fa-bell-o' => '',
							'fa-bitbucket' => '',
							'fa-bitbucket-square' => '',
							'fa-bitcoin' => '',
							'fa-bold' => '',
							'fa-bolt' => '',
							'fa-bomb' => '',
							'fa-book' => '',
							'fa-bookmark' => '',
							'fa-bookmark-o' => '',
							'fa-briefcase' => '',
							'fa-btc' => '',
							'fa-bug' => '',
							'fa-building' => '',
							'fa-building-o' => '',
							'fa-bullhorn' => '',
							'fa-bullseye' => '',
							'fa-cab' => '',
							'fa-calendar' => '',
							'fa-calendar-o' => '',
							'fa-camera' => '',
							'fa-camera-retro' => '',
							'fa-car' => '',
							'fa-caret-down' => '',
							'fa-caret-left' => '',
							'fa-caret-right' => '',
							'fa-caret-square-o-down' => '',
							'fa-caret-square-o-left' => '',
							'fa-caret-square-o-right' => '',
							'fa-caret-square-o-up' => '',
							'fa-caret-up' => '',
							'fa-certificate' => '',
							'fa-chain' => '',
							'fa-chain-broken' => '',
							'fa-check' => '',
							'fa-check-circle' => '',
							'fa-check-circle-o' => '',
							'fa-check-square' => '',
							'fa-check-square-o' => '',
							'fa-chevron-circle-down' => '',
							'fa-chevron-circle-left' => '',
							'fa-chevron-circle-right' => '',
							'fa-chevron-circle-up' => '',
							'fa-chevron-down' => '',
							'fa-chevron-left' => '',
							'fa-chevron-right' => '',
							'fa-chevron-up' => '',
							'fa-child' => '',
							'fa-circle' => '',
							'fa-circle-o' => '',
							'fa-circle-o-notch' => '',
							'fa-circle-thin' => '',
							'fa-clipboard' => '',
							'fa-clock-o' => '',
							'fa-cloud' => '',
							'fa-cloud-download' => '',
							'fa-cloud-upload' => '',
							'fa-cny' => '',
							'fa-code' => '',
							'fa-code-fork' => '',
							'fa-codepen' => '',
							'fa-coffee' => '',
							'fa-cog' => '',
							'fa-cogs' => '',
							'fa-columns' => '',
							'fa-comment' => '',
							'fa-comment-o' => '',
							'fa-comments' => '',
							'fa-comments-o' => '',
							'fa-compass' => '',
							'fa-compress' => '',
							'fa-copy' => '',
							'fa-credit-card' => '',
							'fa-crop' => '',
							'fa-crosshairs' => '',
							'fa-css3' => '',
							'fa-cube' => '',
							'fa-cubes' => '',
							'fa-cut' => '',
							'fa-cutlery' => '',
							'fa-dashboard' => '',
							'fa-database' => '',
							'fa-dedent' => '',
							'fa-delicious' => '',
							'fa-desktop' => '',
							'fa-deviantart' => '',
							'fa-digg' => '',
							'fa-dollar' => '',
							'fa-dot-circle-o' => '',
							'fa-download' => '',
							'fa-dribbble' => '',
							'fa-dropbox' => '',
							'fa-drupal' => '',
							'fa-edit' => '',
							'fa-eject' => '',
							'fa-ellipsis-h' => '',
							'fa-ellipsis-v' => '',
							'fa-empire' => '',
							'fa-envelope' => '',
							'fa-envelope-o' => '',
							'fa-envelope-square' => '',
							'fa-eraser' => '',
							'fa-eur' => '',
							'fa-euro' => '',
							'fa-exchange' => '',
							'fa-exclamation' => '',
							'fa-exclamation-circle' => '',
							'fa-exclamation-triangle' => '',
							'fa-expand' => '',
							'fa-external-link' => '',
							'fa-external-link-square' => '',
							'fa-eye' => '',
							'fa-eye-slash' => '',
							'fa-facebook' => '',
							'fa-facebook-square' => '',
							'fa-fast-backward' => '',
							'fa-fast-forward' => '',
							'fa-fax' => '',
							'fa-female' => '',
							'fa-fighter-jet' => '',
							'fa-file' => '',
							'fa-file-archive-o' => '',
							'fa-file-audio-o' => '',
							'fa-file-code-o' => '',
							'fa-file-excel-o' => '',
							'fa-file-image-o' => '',
							'fa-file-movie-o' => '',
							'fa-file-o' => '',
							'fa-file-pdf-o' => '',
							'fa-file-photo-o' => '',
							'fa-file-picture-o' => '',
							'fa-file-powerpoint-o' => '',
							'fa-file-sound-o' => '',
							'fa-file-text' => '',
							'fa-file-text-o' => '',
							'fa-file-video-o' => '',
							'fa-file-word-o' => '',
							'fa-file-zip-o' => '',
							'fa-files-o' => '',
							'fa-film' => '',
							'fa-filter' => '',
							'fa-fire' => '',
							'fa-fire-extinguisher' => '',
							'fa-flag' => '',
							'fa-flag-checkered' => '',
							'fa-flag-o' => '',
							'fa-flash' => '',
							'fa-flask' => '',
							'fa-flickr' => '',
							'fa-floppy-o' => '',
							'fa-folder' => '',
							'fa-folder-o' => '',
							'fa-folder-open' => '',
							'fa-folder-open-o' => '',
							'fa-font' => '',
							'fa-forward' => '',
							'fa-foursquare' => '',
							'fa-frown-o' => '',
							'fa-gamepad' => '',
							'fa-gavel' => '',
							'fa-gbp' => '',
							'fa-ge' => '',
							'fa-gear' => '',
							'fa-gears' => '',
							'fa-gift' => '',
							'fa-git' => '',
							'fa-git-square' => '',
							'fa-github' => '',
							'fa-github-alt' => '',
							'fa-github-square' => '',
							'fa-gittip' => '',
							'fa-glass' => '',
							'fa-globe' => '',
							'fa-google' => '',
							'fa-google-plus' => '',
							'fa-google-plus-square' => '',
							'fa-graduation-cap' => '',
							'fa-group' => '',
							'fa-h-square' => '',
							'fa-hacker-news' => '',
							'fa-hand-o-down' => '',
							'fa-hand-o-left' => '',
							'fa-hand-o-right' => '',
							'fa-hand-o-up' => '',
							'fa-hdd-o' => '',
							'fa-header' => '',
							'fa-headphones' => '',
							'fa-heart' => '',
							'fa-heart-o' => '',
							'fa-history' => '',
							'fa-home' => '',
							'fa-hospital-o' => '',
							'fa-html5' => '',
							'fa-image' => '',
							'fa-inbox' => '',
							'fa-indent' => '',
							'fa-info' => '',
							'fa-info-circle' => '',
							'fa-inr' => '',
							'fa-instagram' => '',
							'fa-institution' => '',
							'fa-italic' => '',
							'fa-joomla' => '',
							'fa-jpy' => '',
							'fa-jsfiddle' => '',
							'fa-key' => '',
							'fa-keyboard-o' => '',
							'fa-krw' => '',
							'fa-language' => '',
							'fa-laptop' => '',
							'fa-leaf' => '',
							'fa-legal' => '',
							'fa-lemon-o' => '',
							'fa-level-down' => '',
							'fa-level-up' => '',
							'fa-life-bouy' => '',
							'fa-life-ring' => '',
							'fa-life-saver' => '',
							'fa-lightbulb-o' => '',
							'fa-link' => '',
							'fa-linkedin' => '',
							'fa-linkedin-square' => '',
							'fa-linux' => '',
							'fa-list' => '',
							'fa-list-alt' => '',
							'fa-list-ol' => '',
							'fa-list-ul' => '',
							'fa-location-arrow' => '',
							'fa-lock' => '',
							'fa-long-arrow-down' => '',
							'fa-long-arrow-left' => '',
							'fa-long-arrow-right' => '',
							'fa-long-arrow-up' => '',
							'fa-magic' => '',
							'fa-magnet' => '',
							'fa-mail-forward' => '',
							'fa-mail-reply' => '',
							'fa-mail-reply-all' => '',
							'fa-male' => '',
							'fa-map-marker' => '',
							'fa-maxcdn' => '',
							'fa-medkit' => '',
							'fa-meh-o' => '',
							'fa-microphone' => '',
							'fa-microphone-slash' => '',
							'fa-minus' => '',
							'fa-minus-circle' => '',
							'fa-minus-square' => '',
							'fa-minus-square-o' => '',
							'fa-mobile' => '',
							'fa-mobile-phone' => '',
							'fa-money' => '',
							'fa-moon-o' => '',
							'fa-mortar-board' => '',
							'fa-music' => '',
							'fa-navicon' => '',
							'fa-openid' => '',
							'fa-outdent' => '',
							'fa-pagelines' => '',
							'fa-paper-plane' => '',
							'fa-paper-plane-o' => '',
							'fa-paperclip' => '',
							'fa-paragraph' => '',
							'fa-paste' => '',
							'fa-pause' => '',
							'fa-paw' => '',
							'fa-pencil' => '',
							'fa-pencil-square' => '',
							'fa-pencil-square-o' => '',
							'fa-phone' => '',
							'fa-phone-square' => '',
							'fa-photo' => '',
							'fa-picture-o' => '',
							'fa-pied-piper' => '',
							'fa-pied-piper-alt' => '',
							'fa-pied-piper-square' => '',
							'fa-pinterest' => '',
							'fa-pinterest-square' => '',
							'fa-plane' => '',
							'fa-play' => '',
							'fa-play-circle' => '',
							'fa-play-circle-o' => '',
							'fa-plus' => '',
							'fa-plus-circle' => '',
							'fa-plus-square' => '',
							'fa-plus-square-o' => '',
							'fa-power-off' => '',
							'fa-print' => '',
							'fa-puzzle-piece' => '',
							'fa-qq' => '',
							'fa-qrcode' => '',
							'fa-question' => '',
							'fa-question-circle' => '',
							'fa-quote-left' => '',
							'fa-quote-right' => '',
							'fa-ra' => '',
							'fa-random' => '',
							'fa-rebel' => '',
							'fa-recycle' => '',
							'fa-reddit' => '',
							'fa-reddit-square' => '',
							'fa-refresh' => '',
							'fa-renren' => '',
							'fa-reorder' => '',
							'fa-repeat' => '',
							'fa-reply' => '',
							'fa-reply-all' => '',
							'fa-retweet' => '',
							'fa-rmb' => '',
							'fa-road' => '',
							'fa-rocket' => '',
							'fa-rotate-left' => '',
							'fa-rotate-right' => '',
							'fa-rouble' => '',
							'fa-rss' => '',
							'fa-rss-square' => '',
							'fa-rub' => '',
							'fa-ruble' => '',
							'fa-rupee' => '',
							'fa-save' => '',
							'fa-scissors' => '',
							'fa-search' => '',
							'fa-search-minus' => '',
							'fa-search-plus' => '',
							'fa-send' => '',
							'fa-send-o' => '',
							'fa-share' => '',
							'fa-share-alt' => '',
							'fa-share-alt-square' => '',
							'fa-share-square' => '',
							'fa-share-square-o' => '',
							'fa-shield' => '',
							'fa-shopping-cart' => '',
							'fa-sign-in' => '',
							'fa-sign-out' => '',
							'fa-signal' => '',
							'fa-sitemap' => '',
							'fa-skype' => '',
							'fa-slack' => '',
							'fa-sliders' => '',
							'fa-smile-o' => '',
							'fa-sort' => '',
							'fa-sort-alpha-asc' => '',
							'fa-sort-alpha-desc' => '',
							'fa-sort-amount-asc' => '',
							'fa-sort-amount-desc' => '',
							'fa-sort-asc' => '',
							'fa-sort-desc' => '',
							'fa-sort-down' => '',
							'fa-sort-numeric-asc' => '',
							'fa-sort-numeric-desc' => '',
							'fa-sort-up' => '',
							'fa-soundcloud' => '',
							'fa-space-shuttle' => '',
							'fa-spinner' => '',
							'fa-spoon' => '',
							'fa-spotify' => '',
							'fa-square' => '',
							'fa-square-o' => '',
							'fa-stack-exchange' => '',
							'fa-stack-overflow' => '',
							'fa-star' => '',
							'fa-star-half' => '',
							'fa-star-half-empty' => '',
							'fa-star-half-full' => '',
							'fa-star-half-o' => '',
							'fa-star-o' => '',
							'fa-steam' => '',
							'fa-steam-square' => '',
							'fa-step-backward' => '',
							'fa-step-forward' => '',
							'fa-stethoscope' => '',
							'fa-stop' => '',
							'fa-strikethrough' => '',
							'fa-stumbleupon' => '',
							'fa-stumbleupon-circle' => '',
							'fa-subscript' => '',
							'fa-suitcase' => '',
							'fa-sun-o' => '',
							'fa-superscript' => '',
							'fa-support' => '',
							'fa-table' => '',
							'fa-tablet' => '',
							'fa-tachometer' => '',
							'fa-tag' => '',
							'fa-tags' => '',
							'fa-tasks' => '',
							'fa-taxi' => '',
							'fa-tencent-weibo' => '',
							'fa-terminal' => '',
							'fa-text-height' => '',
							'fa-text-width' => '',
							'fa-th' => '',
							'fa-th-large' => '',
							'fa-th-list' => '',
							'fa-thumb-tack' => '',
							'fa-thumbs-down' => '',
							'fa-thumbs-o-down' => '',
							'fa-thumbs-o-up' => '',
							'fa-thumbs-up' => '',
							'fa-ticket' => '',
							'fa-times' => '',
							'fa-times-circle' => '',
							'fa-times-circle-o' => '',
							'fa-tint' => '',
							'fa-toggle-down' => '',
							'fa-toggle-left' => '',
							'fa-toggle-right' => '',
							'fa-toggle-up' => '',
							'fa-trash-o' => '',
							'fa-tree' => '',
							'fa-trello' => '',
							'fa-trophy' => '',
							'fa-truck' => '',
							'fa-try' => '',
							'fa-tumblr' => '',
							'fa-tumblr-square' => '',
							'fa-turkish-lira' => '',
							'fa-twitter' => '',
							'fa-twitter-square' => '',
							'fa-umbrella' => '',
							'fa-underline' => '',
							'fa-undo' => '',
							'fa-university' => '',
							'fa-unlink' => '',
							'fa-unlock' => '',
							'fa-unlock-alt' => '',
							'fa-unsorted' => '',
							'fa-upload' => '',
							'fa-usd' => '',
							'fa-user' => '',
							'fa-user-md' => '',
							'fa-users' => '',
							'fa-video-camera' => '',
							'fa-vimeo-square' => '',
							'fa-vine' => '',
							'fa-vk' => '',
							'fa-volume-down' => '',
							'fa-volume-off' => '',
							'fa-volume-up' => '',
							'fa-warning' => '',
							'fa-wechat' => '',
							'fa-weibo' => '',
							'fa-weixin' => '',
							'fa-wheelchair' => '',
							'fa-windows' => '',
							'fa-won' => '',
							'fa-wordpress' => '',
							'fa-wrench' => '',
							'fa-xing' => '',
							'fa-xing-square' => '',
							'fa-yahoo' => '',
							'fa-yen' => '',
							'fa-youtube' => '',
							'fa-youtube-play' => '',
							'fa-youtube-square' => '',
						),
					),
					array (
						'key' => 'field_55a1a84b5783b',
						'label' => 'Link',
						'name' => 'arfi_header_icons_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Icon',
			),
			array (
				'key' => 'field_55a1a75884b9b',
				'label' => 'Search',
				'name' => 'arfi_header_search',
				'type' => 'true_false',
				'instructions' => 'Hide search icon in menu.',
				'message' => 'Hide',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55a1a790176af',
				'label' => 'Icons',
				'name' => 'arfi_header_icons_hide',
				'type' => 'true_false',
				'instructions' => 'Hide social icons in menu.',
				'message' => 'Hide',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55a1a324ee88f',
				'label' => 'Footer',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55a1bf511faaa',
				'label' => 'Copyright',
				'name' => 'arfi_footer_copyrights',
				'type' => 'textarea',
				'instructions' => 'Write a copyright.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_55a1a327ee890',
				'label' => 'Custom CSS',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55b850e245b60',
				'label' => 'Main CSS code',
				'name' => 'arfi_custom_css',
				'type' => 'textarea',
				'instructions' => 'If you know how to change and want to, you can write here your custom CSS code.',
				'default_value' => '',
				'placeholder' => 'CSS code',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_55b8514875edc',
				'label' => 'Large Devices (1200px and smaller)',
				'name' => 'arfi_custom_css_large_devices',
				'type' => 'textarea',
				'instructions' => 'If you know how to change and want to, you can write here your custom CSS code.',
				'default_value' => '',
				'placeholder' => 'CSS code',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_55b8514b75edd',
				'label' => 'Medium Devices (992px and smaller)',
				'name' => 'arfi_custom_css_medium_devices',
				'type' => 'textarea',
				'instructions' => 'If you know how to change and want to, you can write here your custom CSS code.',
				'default_value' => '',
				'placeholder' => 'CSS code',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_55b8515575ede',
				'label' => 'Small Devices	(768px and smaller)',
				'name' => 'arfi_custom_css_small_devices',
				'type' => 'textarea',
				'instructions' => 'If you know how to change and want to, you can write here your custom CSS code.',
				'default_value' => '',
				'placeholder' => 'CSS code',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_55b8515f75edf',
				'label' => 'Extra Small Devices (480px and smaller)',
				'name' => 'arfi_custom_css_xsmall_devices',
				'type' => 'textarea',
				'instructions' => 'If you know how to change and want to, you can write here your custom CSS code.',
				'default_value' => '',
				'placeholder' => 'CSS code',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-theme-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


 ?>